# Generated by Django 6.0.2 on 2026-03-11 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-attempt_time']},
        ),

        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['-start_time'],
                     'permissions': [('view_all_mailings',
                                      'Can view all mailings')]},
        ),

        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['subject'],
                     'permissions': [('view_all_messages',
                                     'Can view all messages')]},
        ),

        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['email'],
                     'permissions': [('view_all_recipients',
                                     'Can view all recipients')]},
        ),

        migrations.AddField(
            model_name='attempt',
            name='owner',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.
                                    deletion.CASCADE,
                                    related_name='attempts',
                                    to=settings.AUTH_USER_MODEL),
        ),

        migrations.AlterField(
            model_name='attempt',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.
                                    deletion.CASCADE,
                                    related_name='attempts',
                                    to='mailings.mailing'),
        ),

        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Успешно'),
                                            ('FAILED', 'Не успешно')],
                                   max_length=10),
        ),

        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.
                                    deletion.CASCADE,
                                    related_name='mailings',
                                    to='mailings.message'),
        ),

        migrations.AlterField(
            model_name='mailing',
            name='owner',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.
                                    deletion.CASCADE,
                                    related_name='mailings',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(related_name='mailings',
                                         to='mailings.recipient'),
        ),
        migrations.AlterField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.
                                    deletion.CASCADE,
                                    related_name='messages',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='owner',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.
                                    deletion.CASCADE,
                                    related_name='recipients',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
